title: Francesco Fabbri
url: "https://frafabbri.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl: "" # the subpath of your site, e.g. "/blog"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/frafabbri"
footer_text: ""

sass:
    style: expanded
    sass_dir: _sass

